# modules/emailer.py
# Job: Send email alerts when High/Critical risks are found

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import pandas as pd


def send_alert_email(sender: str, password: str, recipient: str,
                     df: pd.DataFrame, scan_time: str) -> bool:
    """
    Send an HTML alert email for High/Critical findings.
    Returns True if sent successfully, False if failed.
    """
    # Only alert for High and Critical findings
    alert_df = df[df['severity'].isin(['High', 'Critical'])].copy()
    count    = len(alert_df)

    if count == 0:
        return False  # nothing to alert about

    # Build HTML table rows
    rows_html = ''
    for i, (_, row) in enumerate(alert_df.iterrows()):
        bg    = '#f9fafb' if i % 2 == 0 else '#ffffff'
        color = '#dc2626' if row['severity'] == 'Critical' else '#ea580c'
        rows_html += f'''
        <tr style="background:{bg};">
            <td style="padding:10px;font-family:monospace;">{row.get("ip","")}</td>
            <td style="padding:10px;">{row.get("port","")}</td>
            <td style="padding:10px;">{row.get("service","")}</td>
            <td style="padding:10px;color:{color};font-weight:bold;">{row.get("severity","")}</td>
            <td style="padding:10px;text-align:center;">{row.get("risk_score","")}</td>
        </tr>'''

    # Full HTML email
    html = f"""
    <html><body style="font-family:Arial;background:#f3f4f6;padding:20px;">
    <div style="max-width:700px;margin:auto;background:white;border-radius:10px;overflow:hidden;">

        <div style="background:linear-gradient(135deg,#1e3a5f,#dc2626);padding:25px;text-align:center;">
            <h1 style="color:white;margin:0;">🛡️ CyberScan Pro</h1>
            <p style="color:#fca5a5;margin:5px 0 0;">Security Alert — Action Required</p>
        </div>

        <div style="background:#fef2f2;border-left:4px solid #dc2626;padding:15px 25px;">
            <p style="color:#991b1b;font-weight:bold;margin:0;">
                🚨 {count} High/Critical findings detected
            </p>
            <p style="color:#7f1d1d;margin:5px 0 0;">Scan time: {scan_time}</p>
        </div>

        <div style="padding:25px;">
            <table width="100%" style="border-collapse:collapse;border:1px solid #e5e7eb;">
                <tr style="background:#1e3a5f;">
                    <th style="padding:10px;color:white;text-align:left;">IP</th>
                    <th style="padding:10px;color:white;text-align:left;">PORT</th>
                    <th style="padding:10px;color:white;text-align:left;">SERVICE</th>
                    <th style="padding:10px;color:white;text-align:left;">SEVERITY</th>
                    <th style="padding:10px;color:white;text-align:center;">SCORE</th>
                </tr>
                {rows_html}
            </table>
        </div>

        <div style="background:#f9fafb;padding:15px;text-align:center;">
            <p style="color:#9ca3af;font-size:12px;margin:0;">Generated by CyberScan Pro</p>
        </div>
    </div>
    </body></html>
    """

    # Plain text version (backup)
    plain = f'CyberScan Alert: {count} High/Critical findings at {scan_time}\n\n'
    for _, row in alert_df.iterrows():
        plain += f'  {row.get("ip")}:{row.get("port")} [{row.get("service")}] → {row.get("severity")} (score: {row.get("risk_score")})\n'

    # Build email message
    msg            = MIMEMultipart('alternative')
    msg['From']    = sender
    msg['To']      = recipient
    msg['Subject'] = f'🚨 CyberScan Alert — {count} Critical/High Findings | {scan_time}'
    msg.attach(MIMEText(plain, 'plain'))
    msg.attach(MIMEText(html,  'html'))

    # Send via Gmail
    try:
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(sender, password)
        server.send_message(msg)
        server.quit()
        return True
    except Exception as e:
        print(f'Email failed: {e}')
        return False